### ISSUE TITLE
Creating average, mean and median

### ISSUE THREAD

**Issue by ricl** [meteostat/routines#5]
In the USCRN there are fields in their daily dataset for average (calculated from their 5min sampling) and mean ((Tmax+Tmin)/2). Are you planning on doing the same for your daily datasets using the hourly figures?

Adding a daily median at the same time would be useful.

**Comment by clampr** [comment]
At the moment I don't want to add additional columns to the daily dumps. I mean you can still calculate mean and median from the hourly files if it's required.

**Comment by ricl** [comment]
Hi Christian,

Yes I realise that but I wondered if you were going to do it in any case.

For now I will calculate it for myself as you suggest.

Richard

**Comment by ricl** [comment]
P.S. There are 3 fields.

Average, which is calculated from an accumulation of the hourly data.
Mean, which is (Min+Max)/2
Median, which is the 'center' of the hourly data for a day

**Comment by clampr** [comment]
I created an issue for the parameter discussion: https://github.com/meteostat/meteostat-python/issues/62
